server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/vastien/msantiago
          search-paths: config-data
          username: vastien
          password: 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
  application:
    name: config-service
