apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
            - name: MYSQL_DATABASE_PROVEEDOR
              valueFrom:
                configMapKeyRef:
                  name: proveedor
                  key: name
            - name: MYSQL_DATABASE_ACOPIO
              valueFrom:
                configMapKeyRef:
                  name: acopio
                  key: name
            - name: MYSQL_DATABASE_GRASAS
              valueFrom:
                configMapKeyRef:
                  name: grasas
                  key: name
            - name: MYSQL_DATABASE_PLANILLAPAGO
              valueFrom:
                configMapKeyRef:
                  name: planillapago
                  key: name
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


