apiVersion: apps/v1
kind: Deployment
metadata:
  name: planilla-deployment
  labels:
    app: planilla-deployment
spec:
  selector:
    matchLabels:
      app: planillapago-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: planillapago-deployment
    spec:
      containers:
        - name: planillapago
          image: vastien/ms-planillapago
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: planillapago
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: planillapago
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: planillapago-service
  labels:
    app: planillapago-service
spec:
  selector:
    app: planillapago-deployment
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: LoadBalancer