server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/vastien/msantiago
          search-paths: config-data
          username: vastien
          password: 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
  application:
    name: config-service
